[package]
name = "naive_semaphore"
version = "0.1.0"
edition = "2021"
author = "snusnu (SteffenW)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stopwatch = "0.0.7"

[profile.test]
opt-level = 3